# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xXEc13gH8VxYWrPqmWTOiTqOaCcmmrfm
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/Health_Risk_Dataset.csv")

df

df.head(5)

df.tail(5)

df.info()

df.isna().sum()

df.index

x = ["O2_Scale "]
y = ["Oxygen_Saturation"]

plt.bar(x,y)
plt.xlabel("O2_Scale")
plt.ylabel("Oxygen_Saturation")
plt.title("Rispiratory_Scale")
plt.xticks(rotation= 90)

plt.show()

sns.set(style = 'darkgrid', rc = {'figure.figsize':(10, 6)}, font_scale = 0.5)

sns.displot(df["Oxygen_Saturation"])

sns.displot

sns.displot(df['Risk_Level'], bins = 20)

sns.displot(df['Risk_Level'], kde = True)

sns.pairplot(df)

df.head(5)

sns.pairplot(df, hue = "Risk_Level")

sns.pairplot(df, hue = "Risk_Level", palette = 'coolwarm')

sns.stripplot(x = 'O2_Scale', y = 'Oxygen_Saturation', data = df)