# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1acaTC63jrbV9Pxi3k2wjpZnrxpkGoyQl
"""

import numpy as np
import matplotlib.pyplot as plt

# FUNCTIONAL METHOD


x = np.linspace(0,6,12)
y = x**2
x

y

plt.plot(x,y)
plt.show()

# TITLE AND LABEL

plt.xlabel('time period')
plt.ylabel('no.of sales')
plt.title('CUSTOMER  VISIT')
plt.plot(x,y)
plt.show()

x1 = np.linspace(-np.pi, np.pi, 256)
x2 = np.linspace(-np.pi, np.pi, 256)

y1 = np.cos(x1)
y2 = np.sin(x2)

plt.plot(x1 ,y1, x2, y2)
plt.show()

# FIGURESIZE AND dpi

plt.figure(figsize = (10,6) ,dpi =80)

plt.plot(x1,y1)
plt.plot(x2,y2)
plt.show()

#  STYLING FIGURE

plt.figure(figsize = (10,6), dpi = 80)

plt.plot(x1,y1 , 'r-.')
plt.plot(x2,y2 , 'b--')

plt.show()

plt.figure(figsize = (10,6), dpi = 80)

plt.plot(x1, y1, color = 'pink')
plt.plot(x2, y2, color = 'green')

plt.show()

plt.figure(figsize = (10,6), dpi = 80)

plt.plot(x1, y1, color = 'pink', linewidth = 2)
plt.plot(x2, y2, color = 'green', linewidth = 2)
plt.show()

plt.figure(figsize = (10,6), dpi = 80)

plt.plot(x1, y1, color = 'pink', linewidth =2, linestyle = '-.')
plt.plot(x2, y2, color = 'green', linewidth = 2, linestyle = '--')
plt.show()

plt.figure(figsize = (10,6), dpi = 80)

plt.plot(x1, y1, color = 'pink', linewidth = 2, linestyle = '-.')
plt. plot(x2, y2, color = 'green', linewidth = 2 ,linestyle = '--')
plt.xticks ([-np.pi, -np.pi/2,0, np.pi/2, np.pi])
plt.yticks([-1,0, 1])
plt.show()

plt.figure(figsize = (10,6), dpi = 80)

plt.plot (x1, y1, color = 'pink', linewidth = 2 , linestyle = '-.')
plt.plot (x2,y2, color = 'green',linewidth = 2, linestyle = '--')

plt.xticks([-np.pi , -np.pi/2,0, np.pi/2, np.pi], [r'$-\pi$',r'$-\pi/2$',r'$0$',r'$\pi/2$',r'$\pi$'])
plt.yticks([-1,0,1])
plt.show()

