# -*- coding: utf-8 -*-
"""Nlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zRNCTWUj4PmbqqZ1bvPi2olAfcqNpmFI
"""

import pandas as pd

df = pd.read_csv("/content/train.txt")

df

!pip install nltk #Install NLTK library
import nltk
nltk . download('punkt')
nltk.download('punkt_tab')

from nltk.tokenize import word_tokenize

with open('/content/train.txt','r')as file:

tokens = word_tokenize (text)

print(tokens)

nltk.download('stopwords')

from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))
filtered_tokens = [word for word in tokens if word. lower() not in stop_words]

print(filtered_tokens)

from nltk import FreqDist

freq_dist = FreqDist(filtered_tokens)

print(freq_dist)

!pip install wordcloud
import matplotlib . pyplot as plt
from wordcloud import WordCloud


wordcloud =  WordCloud(width = 800,background_color = 'white'). generate(''.join(filtered_tokens))
plt.imshow(wordcloud, interpolation = 'bilinear')
plt.axis('off')
plt.show()

!pip install opencv -python

import cv2
from matplotlib import pyplot as plt

image_ur1 = "/content/Gopuram Images.jpeg"

image = cv2.imread(image_ur1)

plt.imshow(cv2.cvtColor(image,cv2. COLOR_BGR2RGB))
plt.axis('off')
plt.show()

height,width = 500,100
plt.imshow (cv2.cvtColor(resized_image,cv2.COLOR_BGR2RGB))
plt.axis('off')
plt.show()

resized_image = cv2.resize(image, (width, height))

