# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yBRcs2pMJ6fy2YGZFr8ldaJJK7NFnE51
"""

import numpy as np
from numpy import*
arr =array([9,8,7,6])
print(arr)
arr=array([5,6,7.5,8,])
print(arr)
print(arr.dtype)
arr=linspace(6,60,3)
print(arr)
arr=np.arange(5,20)
print(arr)
arr=logspace(5,50,3)
print(arr)
print(arr[1])
print('%2f' %arr[2])


arr=zeros(6,int)
print(arr)
arr=zeros((4,5),int)
print(arr)
arr=zeros((3,4,5),int)
print(arr)


list=[4,5,6,7,8,9]
arr=np.array(list)
print(arr)
list=[3,6,8,5],[1,3,6,9],[2,5,7,5]
arr=np.array(list)
print(arr)

matrix=np.full(4,20)
print(matrix)
matrix=np.full((4,4),30)
print(matrix)

matrix=np.eye(4)
print(matrix)

matrix=np.diag([1,4,3])
print(matrix)

arr=np.random.rand(3)
print(arr)
arr=np.random.rand(5,7)
print(arr)

arr=np.random.rand(5,6,3)
print(arr)


arr=np.random.randint(2,20,(4,4))
print(arr)

arr1=linspace(2,20,21)
print(arr1)


arr2=ones((5,4),int)
print(arr2)


arr1.ndim
arr2.ndim

arr1.shape
arr2.shape

arr1.size
arr2.size

arr1.dtype
arr2.dtype

arr1.data
arr2.data

arr=linspace(0,16,17)
print(arr)

for data in arr:
  print(data,end="")

  print(arr[2:6])
  print(arr[:6])
  print(arr[2:])

arr1=arr[6:]
print(arr1)

arr2=arr1.copy
print(arr2)


a = np.array([[1,3],   #array1
            [4,6]])
b = np.array([[4,5],     #array2
             [5,6]])


print(a+1) #adding 1 toevery element
print(a-2)        #subtracting  2 from each element
print(a.sum())    #sum of array elements
print(a+b)          #adding 2 arrays


arr1 = np.array([[3,5], [5,7]],       #first array
                dtype = np.float64)

arr2 = np.array([[4,5], [5,4]],      #second array
                dtype = np.float64)

sum  = np.add(arr1,arr2)      #adding of two array
print(sum)

sum1 =np.sum(arr1)       # adding of all array elements
print(sum1)

sqrt =np.sqrt(arr1)      #square root of array
print(sqrt)

trans_arr = arr1.T        #transpose of array
print(trans_arr)


# python program to demostrate
# array creation technique


a =np.array([[3,4,5],[6,7,8]], dtype ='float')
print(a)

b =np.array((4,5,6))
print(b)

c =np.zeros((4,5))
print(c)


d =np.full((3,3),6, dtype='complex')
print(d)

e =np.random.random((2,2))
print(e)


f = np.arange(0, 30, 5)
print(f)

g = np.linspace(0,5,10)
print(g)

arr =np. array([[1,2,3,4],
                [5,2,3,4],
                [0,1,2,3,]])
newarr =arr.reshape(2,2,3)
print(arr)
print(newarr)


arr =np.array([[1,2,3], [4,5,6]])
flarr =arr.flatten()
print(arr)
print(flarr)

